description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^1.0.5"
  path_drawing: "^1.0.0"
  flutter: 
    sdk: "flutter"
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.1
  intl: ^0.18.1
  cloud_firestore: ^4.7.1
  get: ^4.6.5
  google_fonts: ^5.1.0

dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
  flutter_lints: ^2.0.0
environment: 
  sdk: ">=3.0.5 <4.0.0"
flutter: 
  assets: 
    - "assets/page-1/images/"
    - "images/"

  uses-material-design: true
